version: "3.9"

services: 
  mssql:
    image: mysql:8.0.31-debian
    environment:
        MYSQL_ROOT_PASSWORD: testroot
    ports:
        - '3306:3306'
    volumes:
        - 'my_db_vol:/var/lib/mssql_db/data'
    networks:
            - myAppNetwork

  sqlerver_db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    # Tags	     Architecture	Dockerfile	     OsVersion	   CreatedTime	LastUpdatedTime
    # 2022-latest	amd64	    No Dockerfile	Ubuntu 20.04	05/31/2022	  11/16/2022
    ports: 
        - '1433:1433'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Asdf1234"
    volumes:
        - 'my_db_vol:/var/lib/sqlerver_db/data'
    networks:
        - myAppNetwork
  
  adminer:
    image: adminer
    restart: always
    networks :
     - myAppNetwork
    ports:
      - 8083:8080

  pgsql:
  
    image: 'postgres:12.13-alpine3.17' 
    ports: 
        - '5432:5432' 
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres' 
    volumes:
        - 'my_db_vol:/var/lib/postgresql/data'
    networks:
        - myAppNetwork
networks:
    myAppNetwork:
        driver: bridge 
volumes:
    my_db_vol:
        driver: local